name: Playwright E2E Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g nx
          npm install

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps

      - name: Inject environment variables
        run: echo "${{ secrets.FIELDWIRE_ENV }}" > .env

      - name: Run E2E tests
        run: npx nx run fieldwire-tests:e2e
